# Generated by Django 3.1.7 on 2022-05-14 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storystream',
            old_name='follower',
            new_name='following',
        ),
    ]
