# Generated by Django 3.0.3 on 2021-02-02 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0002_profile_favorites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_info',
            field=models.TextField(blank=True, default='', max_length=150, null=True),
        ),
    ]
