# Generated by Django 3.0.3 on 2021-02-02 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0003_auto_20210202_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_info',
            field=models.TextField(blank=True, default=' ', max_length=150, null=True),
        ),
    ]
